// Generated by main.pagedraw.json
import React from 'react';
import './basecard.css';


export default class Basecard extends React.Component {
  render() {
    return (
      <div className="basecard-basecard-2">
          <div className="basecard-0">
              <div className="basecard-cardframe-7">
                  <div className="basecard-0-0-0">
                      <div className="basecard-number-9">
                          { this.props.text }
                      </div>
                  </div>
                  <div className="basecard-0-0-1">
                      <img src={this.props.img_src} className="basecard-colorcorner-8" /> 
                  </div>
                  <div className="basecard-0-0-2">
                      <img src={this.props.img_src} className="basecard-colorcenter-5" /> 
                  </div>
              </div>
          </div>
          <div className="basecard-1" /> 
      </div>
    );
  }
};
