// Generated by main.pagedraw.json
import React from 'react';
import Button from './button';
import './betbutton.css';


export default class Betbutton extends React.Component {
  render() {
    return (
      <div className="betbutton-betbutton-1">
          <div className="betbutton-0">
              <div className="betbutton-0-0" /> 
              <div onClick={() => {this.props.betAction(this.props.amount);}} className="betbutton-button-5">
                  <Button text={((this.props.amount < this.props.max_bet && "BET " + this.props.amount.toString()) || "ALL IN")} /> 
              </div>
          </div>
      </div>
    );
  }
};
