// Generated by main.pagedraw.json
import React from 'react';
import Betbutton from './betbutton';
import Checkbutton from './checkbutton';
import './betcheckaction.css';


export default class Betcheckaction extends React.Component {
  render() {
    return (
      <div className="betcheckaction-betcheckaction-6">
          <div className="betcheckaction-0">
              <div className="betcheckaction-0-0">
                  <div className="betcheckaction-0-0-0">
                      <div className="betcheckaction-slider-7">
                          <input type="range" onChange={this.props.handleSliderChange} min={String(this.props.min)} max={String(this.props.max)} value={String(this.props.value)} step="5" />
                      </div>
                  </div>
              </div>
              <div className="betcheckaction-bet_button-2">
                  <Betbutton amount={this.props.value} betAction={this.props.betAction} max_bet={this.props.max} /> 
              </div>
          </div>
          <div className="betcheckaction-1">
              <div className="betcheckaction-check_button-8">
                  <Checkbutton checkAction={this.props.checkAction} /> 
              </div>
          </div>
      </div>
    );
  }
};
