// Generated by main.pagedraw.json
import React from 'react';
import './button.css';


export default class Button extends React.Component {
  render() {
    return (
      <div className="button-button-5">
          <div className="button-0" /> 
          <div className="button-1">
              <div className="button-1-0" /> 
              <div className="button-button_shape-6">
                  <div className="button-1-1-0" /> 
                  <div className="button-1-1-1">
                      <div className="button-1-1-1-0" /> 
                      <div className="button-button_text-5">
                          { this.props.text }
                      </div>
                      <div className="button-1-1-1-2" /> 
                  </div>
                  <div className="button-1-1-2" /> 
              </div>
              <div className="button-1-2" /> 
          </div>
          <div className="button-2" /> 
      </div>
    );
  }
};
