// Generated by main.pagedraw.json
import React from 'react';
import Button from './button';
import './checkbutton.css';


export default class Checkbutton extends React.Component {
  render() {
    return (
      <div className="checkbutton-checkbutton-8">
          <div className="checkbutton-0">
              <div onClick={() => {this.props.checkAction();}} className="checkbutton-button-6">
                  <Button text={"CHECK"} /> 
              </div>
          </div>
      </div>
    );
  }
};
