// Generated by main.pagedraw.json
import React from 'react';
import './chips.css';
import chip from "../images/chip.svg"

export default class Chips extends React.Component {
  render() {
    return (
      <div className="chips-chips-8">
          <div className="chips-0">
              <img src={chip} className="chips-chip-8" /> 
              <div className="chips-0-1">
                  <div className="chips-0-1-0">
                      <div className="chips-amount-0">{ this.props.amount }</div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
