// Generated by main.pagedraw.json
import React from 'react';
import Button from './button';
import './foldbutton.css';


export default class Foldbutton extends React.Component {
  render() {
    return (
      <div className="foldbutton-foldbutton-8">
          <div className="foldbutton-0">
              <div onClick={() => {this.props.foldAction();}} className="foldbutton-button-7">
                  <Button text={"FOLD"} /> 
              </div>
          </div>
      </div>
    );
  }
};
