// Generated by main.pagedraw.json
import React from 'react';
import Headertext from './headertext';
import './headerview.css';


export default class Headerview extends React.Component {
  render() {
    return (
      <div className="headerview-headerview-3">
          <div className="headerview-0">
              <div className="headerview-headertext_instance-6">
                  <Headertext room_key={this.props.room_key} name={this.props.name} /> 
              </div>
          </div>
      </div>
    );
  }
};
