// Generated by main.pagedraw.json
import React from 'react';
import './header.css';


export default class Header extends React.Component {
  render() {
    return (
      <div className="header-header-3">
          <div className="header-0">
              <div className="header-room_label-1">{"Room: "}</div>
              <div className="header-room_key-3">
                  { this.props.room_key }
              </div>
              <div className="header-name_label-8">{"Player: "}</div>
              <div className="header-name-7">{ this.props.name }</div>
          </div>
      </div>
    );
  }
};
