// Generated by main.pagedraw.json
import React from 'react';
import Card from './card';
import './playercards.css';


export default class Playercards extends React.Component {
  render() {
    return (
      <div className="playercards-playercards-5">
          <div className="playercards-0">
              <div className="playercards-0-0">
                  <div className="playercards-0-0-0">
                      <div onClick={this.props.toggleShowCards} className="playercards-show_cards-9">
                          <input type="checkbox" className="playercards-0-0-0-0-0" /> 
                      </div>
                  </div>
              </div>
              <div className="playercards-show_cards_text-7">
                  Show Cards
              </div>
          </div>
          <div className="playercards-1">
              <div className="playercards-card1">
                  <Card color={((this.props.show_cards && this.props.cards[0].color) || "")} text={(this.props.cards[0].number)} /> 
              </div>
              <div className="playercards-card2">
                  <Card color={((this.props.show_cards && this.props.cards[1].color) || "")} text={(this.props.cards[1].number)} /> 
              </div>
          </div>
      </div>
    );
  }
};
