// Generated by main.pagedraw.json
import React from 'react';
import Playercards from './playercards';
import './playercardsview.css';


export default class Playercardsview extends React.Component {
  render() {
    return (
      <div className="playercardsview-playercardsview-2">
          <div className="playercardsview-0">
              <div className="playercardsview-player_cards-2">
                  <Playercards cards={this.props.cards} toggleShowCards={this.props.toggleShowCards} show_cards={this.props.show_cards} /> 
              </div>
          </div>
      </div>
    );
  }
};
